In [56]:
import pandas as pd
from pathlib import Path
import numpy as ny
from nba_api.stats.static import players, teams
from nba_api.stats.endpoints import (
    leaguedashplayerstats, leaguedashplayerclutch, leagueseasonmatchups, PlayerAwards
)

In [76]:
pd.set_option('display.max_columns', None)

In [78]:
players_df = pd.DataFrame(players.get_players())
display(players_df.head())
print(f"Rows: {players_df.shape[0]}, Columns: {players_df.shape[1]}")

display(players_df.columns)
display(players_df.nunique())
display(players_df.duplicated().sum())
display(players_df[players_df['id'] == 1642380])

      id            full_name first_name     last_name  is_active
0  76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1  76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2  76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3     51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4   1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False

Rows: 5103, Columns: 5

Index(['id', 'full_name', 'first_name', 'last_name', 'is_active'], dtype='str')

id            5103
full_name     5063
first_name    1699
last_name     3055
is_active        2
dtype: int64

np.int64(0)

Empty DataFrame
Columns: [id, full_name, first_name, last_name, is_active]
Index: []

In [67]:
lebron_df = pd.DataFrame(players.find_players_by_first_name("Lebron"))
lebron_df

     id     full_name first_name last_name  is_active
0  2544  LeBron James     LeBron     James       True

In [43]:
print(f"Unique Player ID's: {players_df['id'].nunique()}")
print(f"Duplicated Player ID's: {players_df.duplicated(['id']).sum()}")

Unique Player ID's: 5103
Duplicated Player ID's: 0

In [44]:
teams_df = pd.DataFrame(teams.get_teams())
display(teams_df)
print(f"Rows: {teams_df.shape[0]}, Columns: {teams_df.shape[1]}")

display(teams_df.columns)
print(f"Unique Team ID's: {teams_df['id'].nunique()}")
print(f"Duplicated Team ID's: {teams_df.duplicated(['id']).sum()}")

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,San Francisco,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

Rows: 30, Columns: 7

Index(['id', 'full_name', 'abbreviation', 'nickname', 'city', 'state',
       'year_founded'],
      dtype='str')

Unique Team ID's: 30
Duplicated Team ID's: 0

In [45]:
def adv_stats_table() -> pd.DataFrame:
    adv_stats = leaguedashplayerstats.LeagueDashPlayerStats(season="2025-26", 
                                                            measure_type_detailed_defense="Advanced",
                                                            season_type_all_star="Regular Season")
    adv_stats_df = adv_stats.get_data_frames()[0]
    return adv_stats_df.columns

adv_stats_table()

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING', 'OFF_RATING',
       'sp_work_OFF_RATING', 'E_DEF_RATING', 'DEF_RATING',
       'sp_work_DEF_RATING', 'E_NET_RATING', 'NET_RATING',
       'sp_work_NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT',
       'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'E_TOV_PCT', 'EFG_PCT', 'TS_PCT',
       'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'sp_work_PACE',
       'PIE', 'POSS', 'FGM', 'FGA', 'FGM_PG', 'FGA_PG', 'FG_PCT', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'E_OFF_RATING_RANK',
       'OFF_RATING_RANK', 'sp_work_OFF_RATING_RANK', 'E_DEF_RATING_RANK',
       'DEF_RATING_RANK', 'sp_work_DEF_RATING_RANK', 'E_NET_RATING_RANK',
       'NET_RATING_RANK', 'sp_work_NET_RATING_RANK', 'AST_PCT_RANK',
       'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK',
       'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK', 'EFG_PCT_RANK',
       'TS_PCT_RANK', 'USG_PCT_RANK', 'E_USG_PCT_RANK', 'E_PACE_RANK',
       'PACE_RANK', 'sp_work_PACE_RANK', 'PIE_RANK', 'FGM_RANK', 'FGA_RANK',
       'FGM_PG_RANK', 'FGA_PG_RANK', 'FG_PCT_RANK', 'TEAM_COUNT'],
      dtype='str')

In [46]:
seasons = [f"{str(season)}-{str(season + 1)[-2:]}" for season in range(2004, 2026)]

print(seasons)

['2004-05', '2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25', '2025-26']

In [47]:
clutch_stats = leaguedashplayerclutch.LeagueDashPlayerClutch(season=2025-26, measure_type_detailed_defense="Advanced", season_type_all_star="Regular Season")

clutch_stats_df = clutch_stats.get_data_frames()[0]
clutch_stats_df.columns

Index(['GROUP_SET', 'PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN',
       'E_OFF_RATING', 'OFF_RATING', 'sp_work_OFF_RATING', 'E_DEF_RATING',
       'DEF_RATING', 'sp_work_DEF_RATING', 'E_NET_RATING', 'NET_RATING',
       'sp_work_NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT',
       'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'E_TOV_PCT', 'EFG_PCT', 'TS_PCT',
       'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'sp_work_PACE',
       'PIE', 'POSS', 'FGM', 'FGA', 'FGM_PG', 'FGA_PG', 'FG_PCT', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'E_OFF_RATING_RANK',
       'OFF_RATING_RANK', 'sp_work_OFF_RATING_RANK', 'E_DEF_RATING_RANK',
       'DEF_RATING_RANK', 'sp_work_DEF_RATING_RANK', 'E_NET_RATING_RANK',
       'NET_RATING_RANK', 'sp_work_NET_RATING_RANK', 'AST_PCT_RANK',
       'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK',
       'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK', 'EFG_PCT_RANK',
       'TS_PCT_RANK', 'USG_PCT_RANK', 'E_USG_PCT_RANK', 'E_PACE_RANK',
       'PACE_RANK', 'sp_work_PACE_RANK', 'PIE_RANK', 'FGM_RANK', 'FGA_RANK',
       'FGM_PG_RANK', 'FGA_PG_RANK', 'FG_PCT_RANK', 'TEAM_COUNT'],
      dtype='str')

In [51]:
base_path = Path("cached_data")
full_path = base_path / "test.txt"
print(full_path)

cached_data/test.txt

In [55]:
primary_defenders_df = leagueseasonmatchups.LeagueSeasonMatchups(season="2025-26",season_type_playoffs="Regular Season").get_data_frames()[0]
primary_defenders_df.columns

Index(['SEASON_ID', 'OFF_PLAYER_ID', 'OFF_PLAYER_NAME', 'DEF_PLAYER_ID',
       'DEF_PLAYER_NAME', 'GP', 'MATCHUP_MIN', 'PARTIAL_POSS', 'PLAYER_PTS',
       'TEAM_PTS', 'MATCHUP_AST', 'MATCHUP_TOV', 'MATCHUP_BLK', 'MATCHUP_FGM',
       'MATCHUP_FGA', 'MATCHUP_FG_PCT', 'MATCHUP_FG3M', 'MATCHUP_FG3A',
       'MATCHUP_FG3_PCT', 'HELP_BLK', 'HELP_FGM', 'HELP_FGA', 'HELP_FG_PERC',
       'MATCHUP_FTM', 'MATCHUP_FTA', 'SFL', 'MATCHUP_TIME_SEC'],
      dtype='str')

In [71]:
player_awards_df = PlayerAwards(player_id=2544).get_data_frames()[0]
display(player_awards_df.columns)
display(player_awards_df.shape)
player_awards_df

Index(['PERSON_ID', 'FIRST_NAME', 'LAST_NAME', 'TEAM', 'DESCRIPTION',
       'ALL_NBA_TEAM_NUMBER', 'SEASON', 'MONTH', 'WEEK', 'CONFERENCE', 'TYPE',
       'SUBTYPE1', 'SUBTYPE2', 'SUBTYPE3'],
      dtype='str')

(188, 14)

,PERSON_ID,FIRST_NAME,LAST_NAME,TEAM,DESCRIPTION,ALL_NBA_TEAM_NUMBER,SEASON,MONTH,WEEK,CONFERENCE,TYPE,SUBTYPE1,SUBTYPE2,SUBTYPE3
0,2544,LeBron,James,Cleveland Cavaliers,All-Defensive Team,1,2008-09,NaN,NaN,1610612739,Award,Kia Motors,KIADT,NaN
1,2544,LeBron,James,Cleveland Cavaliers,All-Defensive Team,1,2009-10,NaN,NaN,1610612739,Award,Kia Motors,KIADT,NaN
2,2544,LeBron,James,Miami Heat,All-Defensive Team,1,2010-11,NaN,NaN,1610612748,Award,Kia Motors,KIADT,NaN
3,2544,LeBron,James,Miami Heat,All-Defensive Team,1,2011-12,NaN,NaN,1610612748,Award,Kia Motors,KIADT,NaN
4,2544,LeBron,James,Miami Heat,All-Defensive Team,1,2012-13,NaN,NaN,1610612748,Award,Kia Motors,KIADT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,2544,LeBron,James,Cleveland Cavaliers,NBA Sporting News Rookie of the Year,NaN,2003-04,NaN,NaN,NaN,Award,Sporting News,SNROY,NaN
184,2544,LeBron,James,USA,Olympic Bronze Medal,NaN,2004,NaN,NaN,NaN,Award,Olympic,Bronze,NaN
185,2544,LeBron,James,USA,Olympic Gold Medal,NaN,2008,NaN,NaN,NaN,Award,Olympic,Gold,NaN
186,2544,LeBron,James,USA,Olympic Gold Medal,NaN,2012,NaN,NaN,NaN,Award,Olympic,Gold,NaN
187,2544,LeBron,James,USA,Olympic Gold Medal,NaN,2024,NaN,NaN,NaN,Award,Olympic,Gold,NaN

In [77]:
player_awards_df["SEASON"].unique()

<ArrowStringArray>
['2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14', '2004-05',
 '2005-06', '2006-07', '2007-08', '2014-15', '2015-16', '2016-17', '2017-18',
 '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25',
 '2003-04', '2025-26',    '2004',    '2008',    '2012',    '2024']
Length: 27, dtype: str

In [82]:
players_ids = players_df['id']
players_ids

0         76001
1         76002
2         76003
3            51
4          1505
         ...
5098      78650
5099    1641783
5100    1628427
5101    1642365
5102     203967
Name: id, Length: 5103, dtype: int64